name: Deploy to Production

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.ACCESS_KEY }}
          source: target/*.jar
          target: /home/${{ secrets.USER }}/quiz-portal

      - name: Restart Spring Boot App on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.ACCESS_KEY }}
          script: |
            sudo systemctl stop quiz-portal.service
            sudo systemctl start quiz-portal.service

      - name: Notify Discord on Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\":\"✅ Deployment to - \`${{ github.ref_name }}\` was successful! 🚀\n🧾 Repository: \`${{ github.repository }}\`\n👤 By: \`${{ github.actor }}\`\n🔗 Commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}\"}" \
               ${{ secrets.DISCORD_NOTIFICATION_WEBHOOK_URL }}

      - name: Notify Discord on Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\":\"❌ Deployment to - \`${{ github.ref_name }}\` failed! 🔥\n🧾 Repository: \`${{ github.repository }}\`\n👤 By: \`${{ github.actor }}\`\n🔍 Check logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" \
               ${{ secrets.DISCORD_NOTIFICATION_WEBHOOK_URL }}